version: 1

formatters:
  basic:
    (): uvicorn.logging.DefaultFormatter
    fmt: '%(levelname)s: %(asctime)s | %(message)s'
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  console:
    class: logging.StreamHandler
    formatter: basic
    stream: ext://sys.stdout

loggers:
  uvicorn:
    handlers: ["console"]
    level: INFO
    propagate: True
